services:
  - type: web
    name: gpt-telegram-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: WEBHOOK_SECRET
        value: mysecret123
